root_datapath: "/mnt/juanjuan/cafidata/UI_TransE/data/"
user_map: "/user_map.json"
item_map: "/item_map.json"
visual_features_dict_ori: "/visualfeatures"
visual_features_tensor: "/visualfeatures_indexedtenseor"
item_cates: "/item_cate_set_indexed.json"
cate_items: "/cate_item_set_indexed.json"
item_cates_ori: "/item_cate_set.json"
cate_items_ori: "/cate_item_set.json"